export const config = {
  server: {
    port: parseInt(process.env.SERVER_PORT || '3001', 10),
    websocketPort: parseInt(process.env.WS_PORT || '3002', 10),
  },
  udp: {
    multicastAddress: process.env.MULTICAST_ADDR || '239.255.0.1',
    port: parseInt(process.env.UDP_PORT || '4712', 10),
    interface: process.env.UDP_INTERFACE || '0.0.0.0',
  },
  redis: {
    host: process.env.REDIS_HOST || '127.0.0.1',
    port: parseInt(process.env.REDIS_PORT || '6379', 10),
    db: parseInt(process.env.REDIS_DB || '0', 10),
    streamMaxLen: 100000,
  },
  protocol: {
    version: '2011',
    timeBase: 1000000,
    maxFrameSize: 65535,
  },
  alarm: {
    frequencyHigh: 50.5,
    frequencyLow: 49.5,
    angleDiffMax: 30,
    voltageHigh: 1.1,
    voltageLow: 0.9,
    checkInterval: 100,
  },
  simulation: {
    enabled: true,
    stationCount: 5,
    frameRate: 50,
  },
};

export const STATION_COLORS = [
  '#00f0ff',
  '#ff6b35',
  '#00ff88',
  '#ff3366',
  '#ffdd00',
  '#a855f7',
  '#06b6d4',
  '#f97316',
];

export const DEFAULT_STATIONS = [
  {
    id: 'station-1',
    name: 'STATION_A',
    pmuId: 1,
    ipAddress: '192.168.1.101',
    port: 4712,
    phasorCount: 6,
    analogCount: 0,
    digitalCount: 0,
    nominalVoltage: 220,
    status: 'online' as const,
    color: STATION_COLORS[0],
  },
  {
    id: 'station-2',
    name: 'STATION_B',
    pmuId: 2,
    ipAddress: '192.168.1.102',
    port: 4712,
    phasorCount: 6,
    analogCount: 0,
    digitalCount: 0,
    nominalVoltage: 220,
    status: 'online' as const,
    color: STATION_COLORS[1],
  },
  {
    id: 'station-3',
    name: 'STATION_C',
    pmuId: 3,
    ipAddress: '192.168.1.103',
    port: 4712,
    phasorCount: 6,
    analogCount: 0,
    digitalCount: 0,
    nominalVoltage: 220,
    status: 'online' as const,
    color: STATION_COLORS[2],
  },
  {
    id: 'station-4',
    name: 'STATION_D',
    pmuId: 4,
    ipAddress: '192.168.1.104',
    port: 4712,
    phasorCount: 6,
    analogCount: 0,
    digitalCount: 0,
    nominalVoltage: 220,
    status: 'online' as const,
    color: STATION_COLORS[3],
  },
  {
    id: 'station-5',
    name: 'STATION_E',
    pmuId: 5,
    ipAddress: '192.168.1.105',
    port: 4712,
    phasorCount: 6,
    analogCount: 0,
    digitalCount: 0,
    nominalVoltage: 220,
    status: 'online' as const,
    color: STATION_COLORS[4],
  },
];
